[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
license = "MIT OR Apache-2.0"
name = "floaty"
version = "0.1.0"

[features]
unstable = []

[dependencies.cast]
git = "https://github.com/japaric/cast.rs"
